### ISSUE TITLE
Segmentation Fault on Steam Deck with  0ad-0.0.25b-alpha AppImage

### ISSUE THREAD

**Issue by cosmo-ray** [0ad-matters/0ad-appimage#10]
Hello,

I've try to run 0ad-0.0.25b-alpha.AppImage on my steamdeck in order to run hyrule conquest, with this crappy script
https://github.com/cosmo-ray/steam_deck_howto_game/blob/master/hyrule-conquest-install-here.sh

The script work on my up-to date Arch Linux.
Sadly it seems to segmentation Fault on steam deck.

Note that the version 0.25 is require for hyrule conquest.

Thanks for your help.

Update: I've just test with 0.26, it seems to have the same error.

**Comment by andy5995** [comment]
Unfortunately I don't know how to help with steam deck issues, but I'll leave this ticket open and hopefully someone can.

You might have better luck by asking around in the [AppImage community](https://docs.appimage.org/contact.html) or the [AppImage reddit](https://www.reddit.com/r/AppImage/).

Can you paste in the full output of the seg fault?

Are any files getting created in `~/.config/0ad/logs/` such as the ones mentioned at [~/.config/0ad/logs/](https://trac.wildfiregames.com/wiki/Debugging#Reproducingthecrash) (section:Reproducing the crash)?

You could might get a wee bit more info if you try a [stack trace](https://senarvi.github.io/stack-trace-with-gdb/)

**Comment by cosmo-ray** [comment]
Sadly, the game crash before it can even create the config files.


Here's gdb output
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 10835]
process 10831 is executing new program: /usr/bin/env
process 10831 is executing new program: /usr/bin/bash
[Detaching after fork from child process 10840]
[Detaching after fork from child process 10842]
[Detaching after fork from child process 10843]
process 10831 is executing new program: /usr/bin/env
process 10831 is executing new program: /usr/bin/bash
[Detaching after fork from child process 10846]
[Detaching after fork from child process 10848]
process 10831 is executing new program: /tmp/.mount_0ad-0.2u2Dhn/usr/bin/pyrogenesis

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fd0098 in dl_main () from /lib64/ld-linux-x86-64.so.2
(gdb) bt
#0  0x00007ffff7fd0098 in dl_main () from /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7fe9557 in _dl_sysdep_start () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7fcf0af in _dl_start () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7fce098 in _start () from /lib64/ld-linux-x86-64.so.2
#4  0x0000000000000001 in ?? ()
#5  0x00007fffffffe572 in ?? ()
#6  0x0000000000000000 in ?? ()
(gdb) 
```
